package com.stormpanda.megingiard.ui

import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

val GC_CARD_CORNER = 12.dp
val GC_CARD_MIN_HEIGHT = 56.dp
val GC_CARD_H_PADDING = 16.dp
val GC_CARD_V_PADDING = 12.dp
val GC_FOCUS_BORDER_WIDTH = 2.5.dp
val GC_DEFAULT_BORDER_WIDTH = 1.dp
val GC_FOCUS_ELEVATION = 6.dp
val GC_DEFAULT_ELEVATION = 0.dp
val GC_ICON_BOX_SIZE = 36.dp
val GC_ICON_SIZE = 22.dp
val GC_STATUS_PILL_CORNER = 16.dp
val GC_STATUS_PILL_H_PADDING = 10.dp
val GC_STATUS_PILL_V_PADDING = 4.dp
val GC_STEPPER_BTN_SIZE = 32.dp
val GC_SWATCH_SIZE = 28.dp
val GC_SWATCH_CHECK_ICON_SIZE = 16.dp
val GC_SWATCH_BORDER_WIDTH_ADJUSTING = 3.dp
val GC_SWATCH_BORDER_WIDTH_DEFAULT = 1.dp
val GC_PALETTE_CONTAINER_H_PADDING = 8.dp
val GC_PALETTE_CONTAINER_V_PADDING = 6.dp
val GC_PALETTE_CONTAINER_BORDER_ADJUSTING = 2.dp
val GC_PALETTE_CONTAINER_BORDER_DEFAULT = 1.dp
val GC_COLOR_CARD_CONTENT_SPACING = 8.dp
val GC_SLIDER_HEIGHT = 24.dp
val GC_SLIDER_TRACK_HEIGHT = 8.dp
val GC_ROW_CONTENT_SPACING = 12.dp
val GC_TEXT_SIZE_PILL = 12.sp
val GC_TEXT_SIZE_CAPSULE = 13.sp
val GC_CAPSULE_TEXT_WIDTH = 140.dp
val GC_SPACING_2 = 2.dp
val GC_SPACING_4 = 4.dp
val GC_SPACING_6 = 6.dp
val GC_SPACING_8 = 8.dp
val GC_SPACING_10 = 10.dp
val GC_CORNER_4 = 4.dp
val GC_CORNER_8 = 8.dp

const val GC_CARD_FOCUSED_BG_ALPHA = 0.95f
const val GC_CARD_UNFOCUSED_BG_ALPHA = 0.55f
const val GC_ACCENT_TINT_ALPHA = 0.2f
const val GC_DESTRUCTIVE_BG_ALPHA = 0.15f
const val GC_DESTRUCTIVE_BORDER_ALPHA = 0.6f
const val GC_SWATCH_BORDER_ALPHA = 0.3f
const val GC_SLIDER_TRACK_BORDER_ALPHA = 0.25f
const val GC_ANIM_DURATION_MS = 150
const val GC_SPLIT_ANIM_DURATION_MS = 220
const val GC_UNFOCUSED_MAX_LINES = 2
const val GC_DEFAULT_SLIDER_STEP = 0.05f
const val GC_DISABLED_CARD_ALPHA = 0.38f
const val GC_PULSE_DURATION_MS = 1400
const val GC_PULSE_ACCENT_ALPHA = 0.35f
const val GC_PULSE_SURFACE_ALPHA = 0.55f

val GC_INFO_BOX_RADIUS = 8.dp
const val GC_INFO_BOX_BG_ALPHA = 0.5f
const val GC_INFO_BOX_BORDER_ALPHA = 0.2f
val GC_INFO_BOX_BORDER_WIDTH = 1.dp
val GC_INFO_BOX_PADDING_H = 14.dp
val GC_INFO_BOX_PADDING_V = 12.dp
val GC_INFO_BOX_SPACING = 10.dp
val GC_INFO_BOX_ICON_SIZE = 20.dp
val GC_INFO_BOX_TEXT_SPACING = 2.dp

val GC_CARD_SHAPE = RoundedCornerShape(GC_CARD_CORNER)
val GC_CORNER_8_SHAPE = RoundedCornerShape(GC_CORNER_8)
val GC_STATUS_PILL_SHAPE = RoundedCornerShape(GC_STATUS_PILL_CORNER)
val GC_CORNER_4_SHAPE = RoundedCornerShape(GC_CORNER_4)
val GC_INFO_BOX_SHAPE = RoundedCornerShape(GC_INFO_BOX_RADIUS)
