import java.security.MessageDigest

plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.serialization)
}

// ---------------------------------------------------------------------------
// Generate NativeBinaryHashes.kt by SHA-256-hashing the native injector
// binaries bundled in :app's assets. The generated map is consulted at
// runtime (NativeBinaryInjector.deployBinary) to refuse executing a binary
// that does not match the hash that was committed to the repository.
// ---------------------------------------------------------------------------
val nativeBinaries = listOf(
    "touchinjector_arm64",
    "mouseinjector_arm64",
    "keyinjector_arm64",
    "gamepadinjector_arm64",
    "megingiard_privd_arm64",
    "megingiard_mirror.dex",
)
val assetsDir = rootProject.file("app/src/main/assets")
val generatedHashesDir = layout.buildDirectory.dir("generated/source/nativeBinaryHashes/kotlin")

val generateNativeBinaryHashes = tasks.register("generateNativeBinaryHashes") {
    // The mirror DEX is regenerated by :mirrorserver:dex on every build — make
    // sure we hash the up-to-date bytes that will ship in the APK.
    dependsOn(":mirrorserver:dex")
    val outDir = generatedHashesDir
    inputs.files(nativeBinaries.map { File(assetsDir, it) })
    outputs.dir(outDir)
    doLast {
        val md = MessageDigest.getInstance("SHA-256")
        val entries = nativeBinaries.joinToString(",\n") { name ->
            val f = File(assetsDir, name)
            require(f.exists()) { "Missing native binary asset: ${f.absolutePath}" }
            md.reset()
            val hex = md.digest(f.readBytes())
                .joinToString("") { b -> "%02X".format(b.toInt() and 0xFF) }
            "    \"$name\" to \"$hex\""
        }
        val targetDir = outDir.get().asFile
            .resolve("com/stormpanda/megingiard/security")
        targetDir.mkdirs()
        targetDir.resolve("NativeBinaryHashes.kt").writeText(
            """// AUTO-GENERATED — do not edit. Regenerated by :domain:generateNativeBinaryHashes.
package com.stormpanda.megingiard.security

/**
 * Expected SHA-256 (uppercase hex) of each native injector binary shipped in
 * `app/src/main/assets/`. Computed at build time from the committed bytes and
 * checked at runtime in [com.stormpanda.megingiard.input.NativeBinaryInjector]
 * before the binary is made executable.
 */
internal object NativeBinaryHashes {
    val EXPECTED: Map<String, String> = mapOf(
$entries
    )
}
"""
        )
    }
}

android {
    namespace = "com.stormpanda.megingiard.domain"
    compileSdk = 35

    defaultConfig {
        minSdk = 33

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles("consumer-rules.pro")
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        // debounce() carries @FlowPreview in the binary metadata of coroutines 1.8.x
        // even though the annotation class is no longer exported publicly.
        // Opt-in globally so no import is needed.
        freeCompilerArgs += "-opt-in=kotlinx.coroutines.FlowPreview"
    }
    sourceSets {
        getByName("main") {
            kotlin.srcDir(generatedHashesDir)
        }
    }
}

// Make every Kotlin compile + KSP-like task depend on the generator.
tasks.matching { it.name.startsWith("compile") && it.name.contains("Kotlin") }.configureEach {
    dependsOn(generateNativeBinaryHashes)
}

kotlin {
    jvmToolchain(17)
}

dependencies {
    api(project(":core"))

    implementation(libs.androidx.core.ktx)
    implementation(libs.kotlinx.coroutines.core)
    implementation(libs.kotlinx.coroutines.android)
    implementation(libs.kotlinx.serialization.json)
    implementation(libs.androidx.datastore.preferences)
    implementation(libs.libadb.android)
    implementation(libs.sun.security.android)
    implementation(libs.conscrypt.android)

    testImplementation(libs.junit)
    testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.8.1")
}
